### ISSUE TITLE
switch to different format to support editor tools

### ISSUE THREAD

**Issue by eikaramba** [jacob-8/poly-i18n#1]
i am using i18n-ally for VS code and as you can see here it will not work with .js locale files.
https://github.com/lokalise/i18n-ally/wiki/Locale-Formats

resp. editing will not work. thus i would suggest to switch to a .json file notation.

**Comment by eikaramba** [comment]
doing this is quite easy as the .js files can just be renamed and transformed to json.

then import the json files instead of the js files

**Comment by jacob-8** [comment]
Too funny, we're on the same page. I ran into the same thing today and came to the conclusion that `i18n-ally` no longer works with `.js` files. We're switched over to `.json` now.

**Comment by eikaramba** [comment]
ah nice, btw i needed to put a custom framework file into the settings folder to support the `t('KEY')` notation. the svelte integration only watches for $t symbols.

```
# .vscode/i18n-ally-custom-framework.yml

# An array of strings which contain Language Ids defined by VS Code
# You can check available language ids here: https://code.visualstudio.com/docs/languages/identifiers
languageIds:
  - javascript
  - typescript
  - svelte

# An array of RegExes to find the key usage. **The key should be captured in the first match group**.
# You should unescape RegEx strings in order to fit in the YAML file
# To help with this, you can use https://www.freeformatter.com/json-escape.html
usageMatchRegex:
  # - "[^\\w\\d]t\\(['\"`]({key})['\"`]"
  - "(?:(?:_|t))\\(\\s*[\\'\"`]({key})[\\'\"`]"

# A RegEx to set a custom scope range. This scope will be used as a prefix when detecting keys
# and works like how the i18next framework identifies the namespace scope from the
# useTranslation() hook.
# You should unescape RegEx strings in order to fit in the YAML file
# To help with this, you can use https://www.freeformatter.com/json-escape.html
scopeRangeRegex: "useTranslation\\(\\s*\\[?\\s*['\"`](.*?)['\"`]"

# An array of strings containing refactor templates.
# The "$1" will be replaced by the keypath specified.
# Optional: uncomment the following two lines to use

refactorTemplates:
 - t("$1")


# If set to true, only enables this custom framework (will disable all built-in frameworks)
monopoly: false
```

and then in the settings.json file

```
"i18n-ally.enabledFrameworks": [
        "custom","svelte"
    ],
```

**Comment by jacob-8** [comment]
Thanks for the example! I find that I'm good to go with the following:

```
# An array of strings which contain Language Ids defined by VS Code
# You can check available language ids here: https://code.visualstudio.com/docs/languages/identifiers
languageIds:
  - javascript
  - typescript
  - svelte

# An array of RegExes to find the key usage. **The key should be captured in the first match group**.
# You should unescape RegEx strings in order to fit in the YAML file
# To help with this, you can use https://www.freeformatter.com/json-escape.html
usageMatchRegex:
  - "[^\\w\\d]t\\(['\"`]({key})['\"`]" # i18n-ally's default example of how to detect `t("your.i18n.keys")` - the `{key}` will be placed by a proper keypath matching regex, you can ignore it and use your own matching rules as well

# If set to true, only enables this custom framework (will disable all built-in frameworks)
monopoly: true
```

This uses their default `usageMatchRegex` example) and I don't need to set `i18n-ally.enabledFrameworks`. Tell me more about the scopeRangeRegex and refactorTemplates - do you use those much? I've never.

**Comment by eikaramba** [comment]
honestly i don't even know what scopeRangeRegex does. I think refactorTemplates is used when you extract hard coded strings with the plugin. I actually use that quite often. Just mark some text, extract it and voila the text is placed into the json and the javascript files references the correct key. for simple small websites that is enough esp. with the automatic deepl translations.
for bigger projects with multiple people working on translations GUIs like i18next or inlang however come in handy of course

**Comment by jacob-8** [comment]
> honestly i don't even know what scopeRangeRegex does. I think refactorTemplates is used when you extract hard coded strings with the plugin. I actually use that quite often. Just mark some text, extract it and voila the text is placed into the json and the javascript files references the correct key. for simple small websites that is enough esp. with the automatic deepl translations. for bigger projects with multiple people working on translations GUIs like i18next or inlang however come in handy of course

Makes sense - yeah I translate my strings elsewhere and bring them into the app via a script. Though I'd like to do everything using just the json files as the single source of truth in the future.
