### ISSUE TITLE
how to use on server/form actions endpoints?

### ISSUE THREAD

**Issue by eikaramba** [jacob-8/poly-i18n#2]
i don't see a way how this can currently be used on server endpoints in an easy way. i am having the locale in the path like "/en/my/page" so i could theoretically create a new instance and use it. but if there is a better approach i am all ears

**Comment by eikaramba** [comment]
mhm okay this actually works. i wasn't aware i can access the page store on the server. but i guess you shouldn't really and that this is not guaranteed to be in sync to the users locale.  And also it does seem to only show the fallback.

```js
import { page } from '$app/stores';
import { get } from 'svelte/store';


const login: Action = async ({ cookies, request,locals,url }) => {
console.log(get(page).t)
.....
```

At the top of the endpoint i could do this. the locale variable is populated  in the hooks.server.js file
```js
const t = await getTranslator(locals.locale);
```

**Comment by jacob-8** [comment]
I do not know how the page store works in server endpoints - I didn't even think it was available??? I would not use it. The idea is to instantiate a new translate instance on every server request. So however you get your desired locale to the server endpoint is fine, just make sure to run this in the server endpoint: `const t = await getTranslator({ locale })`

You could pass it from the client with any other data they pass to the endpoint. Or yeah, you could use the URL. Those seems like the two most logical options. Does that answer your question?

**Comment by eikaramba** [comment]
yes i mean i guess there is just no other way, because there is no shared state on the server as far as i know of.
